---
- name: Install and Configure Jenkins on RHEL
  hosts: all
  become: yes
  tasks:
    - name: Update the system
      dnf:
        name: '*'
        state: latest

    - name: Add Jenkins repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Upgrade the system
      dnf:
        name: '*'
        state: latest

    - name: Install required dependencies for Jenkins
      dnf:
        name:
          - fontconfig
          - java-17-openjdk
        state: present

    - name: Configure Java environment variables
      lineinfile:
        path: /etc/profile
        line: "{{ item }}"
        create: yes
      with_items:
        - "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk"
        - "export PATH=$PATH:$JAVA_HOME/bin"

    - name: Source profile
      shell: source /etc/profile
      args:
        executable: /bin/bash

    - name: Verify Java installation
      shell: java -version
      register: java_version
      ignore_errors: yes

    - name: Debug Java version output
      debug:
        var: java_version.stdout

    - name: Install Jenkins
      dnf:
        name: jenkins
        state: present

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable Jenkins service
      systemd:
        name: jenkins.service
        enabled: yes

    - name: Start Jenkins service
      systemd:
        name: jenkins.service
        state: started

    - name: Configure firewall for Jenkins
      firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: Add Jenkins port to firewall
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled

    - name: Reload firewall
      firewalld:
        state: reloaded

    - name: Display access URL
      shell: hostname -I | awk '{print $1}'
      register: ip_address

    - name: Print Jenkins access URL
      debug:
        msg: "Access Jenkins at: http://{{ ip_address.stdout }}:8080"
